# Standard Spring Configuration
spring:
  application:
    name: ticket-booking-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketdb
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Standard Security User
  security:
    user:
      name: dev
      password: dev

application:
  security:
    jwt:
      # 1 day in ms
      expiration: 86400000
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970